packages:
  - dsh-plugin-registry
  - dsh-marketplace

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@deepseek-ai/cordis@4.0.1'
  - '@deepseek-ai/cosmokit@1.8.2'
  - '@deepseek-ai/dsh-home-paths@0.1.0-rc.6'
  - '@deepseek-ai/dsh-host-webserver@0.1.0-rc.6'
  - '@deepseek-ai/dsh-invariants@0.1.0-rc.6'
  - '@deepseek-ai/schemastery@3.18.1'
